swagger: "2.0"
info:
  title: "Factory Management System API"
  description: "API documentation for the Factory Management System"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemas:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /employees/:
    get:
      summary: Get all employees
      responses:
        '200':
          description: Successfully retrieved employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        '429':
          description: Too many requests
    post:
      summary: Add a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '201':
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '429':
          description: Too many requests

  /products/:
    get:
      summary: Get all products
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: per_page
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successfully retrieved products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '429':
          description: Too many requests
    post:
      summary: Add a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '429':
          description: Too many requests

  /orders/:
    get:
      summary: Get all orders
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: per_page
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successfully retrieved orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '429':
          description: Too many requests
    post:
      summary: Add a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '429':
          description: Too many requests

  /customers/:
    get:
      summary: Get all customers
      responses:
        '200':
          description: Successfully retrieved customers
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Customer'
          examples:
            application/json:
              - id: 1
                name: "John Doe"
                email: "johndoe@example.com"
                phone: "123-456-7890"
        '429':
          description: Too many requests
          examples:
            application/json:
              message: "Too many requests"
              status: 429
        '500':
          description: Internal server error
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Internal server error"
              status: 500
    post:
      summary: Add a new customer
      parameters:
        - in: body
          name: customer
          schema:
            $ref: '#/components/schemas/Customer'
          examples:
            application/json:
              name: "Jane Doe"
              email: "janedoe@example.com"
              phone: "098-765-4321"
      responses:
        '201':
          description: Customer created successfully
          schema:
            $ref: '#/components/schemas/Customer'
          examples:
            application/json:
              id: 2
              name: "Jane Doe"
              email: "janedoe@example.com"
              phone: "098-765-4321"
        '400':
          description: Invalid input
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Invalid input"
              status: 400
        '429':
          description: Too many requests
          examples:
            application/json:
              message: "Too many requests"
              status: 429
        '500':
          description: Internal server error
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Internal server error"
              status: 500

  /customers/{customer_id}:
    get:
      summary: Get a customer by ID
      parameters:
        - in: path
          name: customer_id
          type: integer
          required: true
      responses:
        '200':
          description: Successfully retrieved customer
          schema:
            $ref: '#/components/schemas/Customer'
          examples:
            application/json:
              id: 1
              name: "John Doe"
              email: "johndoe@example.com"
              phone: "123-456-7890"
        '404':
          description: Customer not found
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Customer not found"
              status: 404
        '429':
          description: Too many requests
          examples:
            application/json:
              message: "Too many requests"
              status: 429
        '500':
          description: Internal server error
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Internal server error"
              status: 500
    put:
      summary: Update a customer by ID
      parameters:
        - in: path
          name: customer_id
          type: integer
          required: true
        - in: body
          name: customer
          schema:
            $ref: '#/components/schemas/Customer'
          examples:
            application/json:
              name: "John Smith"
              email: "johnsmith@example.com"
              phone: "321-654-0987"
      responses:
        '200':
          description: Customer updated successfully
          schema:
            $ref: '#/components/schemas/Customer'
          examples:
            application/json:
              id: 1
              name: "John Smith"
              email: "johnsmith@example.com"
              phone: "321-654-0987"
        '400':
          description: Invalid input
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Invalid input"
              status: 400
        '404':
          description: Customer not found
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Customer not found"
              status: 404
        '429':
          description: Too many requests
          examples:
            application/json:
              message: "Too many requests"
              status: 429
        '500':
          description: Internal server error
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Internal server error"
              status: 500
    delete:
      summary: Delete a customer by ID
      parameters:
        - in: path
          name: customer_id
          type: integer
          required: true
      responses:
        '200':
          description: Customer deleted successfully
          schema:
            $ref: '#/components/schemas/Customer'
          examples:
            application/json:
              message: "customer deleted successfully"
        '404':
          description: Customer not found
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Customer not found"
              status: 404
        '429':
          description: Too many requests
          examples:
            application/json:
              message: "Too many requests"
              status: 429
        '500':
          description: Internal server error
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            application/json:
              message: "Internal server error"
              status: 500

  /productions/:
    get:
      summary: Get all productions
      responses:
        '200':
          description: Successfully retrieved productions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Production'
        '429':
          description: Too many requests
    post:
      summary: Add a new production
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Production'
      responses:
        '201':
          description: Production created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Production'
        '429':
          description: Too many requests

components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 100
        position:
          type: string
          maxLength: 100
      required:
        - name
        - position

    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 100
        price:
          type: number
          format: float
      required:
        - name
        - price

    Order:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        product_id:
          type: integer
        quantity:
          type: integer
        total_price:
          type: number
          format: float
      required:
        - customer_id
        - product_id
        - quantity
        - total_price

    Customer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 100
        email:
          type: string
          maxLength: 100
        phone:
          type: string
          maxLength: 20
      required:
        - name
        - email
        - phone

    Error:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
      required:
        - message
        - status

    Production:
      type: object
      properties:
        id:
          type: integer
        product_id:
          type: integer
        employee_id:
          type: integer
        quantity_produced:
          type: integer
        date_produced:
          type: string
          format: date
      required:
        - product_id
        - employee_id
        - quantity_produced
        - date_produced

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
